#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Fix Git hook output display issues (for Git 2.36.0+)
if sh -c ": >/dev/tty" >/dev/null 2>/dev/null; then exec >/dev/tty 2>&1; fi

# Run lint-staged
npx lint-staged
